name: Sync branches with main

on:
  push:
    branches: 
      - main
  schedule:
    - cron: "0 2 * * *"
  
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get all branches
        run: |
          git fetch --all
          git branch -r

      - name: Merge main into other branches
        run: |
          for branch in $(git branch -r | grep -vE "main|HEAD" | sed 's/origin\///'); do
            echo "Merging main into $branch..."
            git checkout $branch
            git merge origin/main --no-edit || true
            git push origin $branch || true
          done
